### PR TITLE
Add DB forum post schema.

### PR DESCRIPTION
**Pull request by kimslor**
# Description

Added a database schema for a forum post using mongoose.
This should be used when a new forum post is created.

## Related Issue

Solves https://github.com/SE701-T5/Backend/issues/33

## Type of change

- [x] New feature (enhancement)

## How Has This Been Tested?

This schema has not been tested.

# Checklist:

- [x] Does a similar (open or closed) pull request not already exist?
- [x] Is the pull request _head_ repository a fork repository?
- [x] Is the pull request _compare_ branch a development branch?
- [x] Is the code documented, particularly in hard-to-understand areas?
- [x] Does the code build without new warnings?
- [x] Has testing been performed that proves changes are effective and work?
- [x] Has a self- and/or peer-review of the code been performed?
- [x] Have dependent changes been merged and published in downstream modules?
- [x] Does all new and existing automated testing pass?
- [x] Is the person responsible for the repository assigned to the pull request?
- [x] Is the pull request linked to a project?
- [x] Is the pull request linked to a milestone?

For more information, refer to the [Contributing Guidelines](../blob/contribution-guidelines/.github/CONTRIBUTING.md) document.

### CODE REVIEW

**Review by R055A — CHANGES_REQUESTED** [review]
I don't think the model directory is the correct place for a schema. 

Could you move the schema to config and maybe make a new subdirectory for schemas?

**Comment by kimslor** [comment]
@R055A The changes you requested have been made. Could you please re-review it? Thanks.

**Review by R055A — CHANGES_REQUESTED** [review]
I think it could be a good idea to include date and time. The test passes.

**Comment by kimslor** [comment]
@R055A timestamps have been added for date-time attributes. It will assign createdAt and updatedAt fields.

**Review by R055A — APPROVED** [review]
LGTM!

**Pull request merged**
